import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MultiDST",
  description: "Generated by create next app for Team MultiDST",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={inter.className}>
        <Navbar />
        <div className="gradient flex flex-col bg-cover bg-center py-4 px-[10%] bg-fixed min-h-screen">
        {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
